# docker-compose.yml
services:
  jekyll:
    build: .
    command: bundle exec jekyll serve --host 0.0.0.0 --force_polling --trace
    ports:
      - "4030:4000"
    volumes:
      - "./src:/srv/jekyll"
      - bundle_cache:/usr/local/bundle
volumes:
  bundle_cache:
