baseurl: "/"
permalink: pretty
title: "だらけた日記"

logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32"
  mobile_width: "32"
  desktop: "images/logo/logo.svg"
  desktop_height: "32"
  desktop_width: "120"

home:
  limit_services: 6

collections:
  tech:
    output: true
    sort_by: weight
  learning:
    output: true

defaults:
  - scope:
      path: ""
      type: "tech"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "learning"
    values:
      layout: "learning"

sass:
  style: compressed

timezone: Asia/Tokyo

future: true

plugins:
  - jekyll-environment-variables
  - jekyll-sitemap

include:
  - "e7019bb5a01c4f44a471c9ee4471e030.txt"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
