name: Build Jekyll and Deploy to Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master # ここで、pushイベントはmasterブランチに制限されます。

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' # ここで、イベント名が'push'であるかどうかを確認します。
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      # Rubyをセットアップします。
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      # Jekyllと依存関係をインストールします。
      - name: Install Jekyll and dependencies
        env:
          JEKYLL_VERSION: 3.8.0
          RUBYGEMS_VERSION: 2.7.6
          BUNDLER_VERSION: 1.16.1
        run: |
          gem install bundler
          gem install rouge
          gem install jekyll
          cd src
          bundle install

      # Jekyll サイトをビルドします。
      - name: Build Jekyll site
        env:
          JEKYLL_ENV: production
        run: |
          cd src
          bundle exec jekyll build

      # Azure にビルドされたサイトをデプロイします。
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_MOSS_085CF2E00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "src/_site"
          api_location: ""
          output_location: "/"
